# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


source = ~/.config/hypr/config/defaults.conf


exec = nwg-drawer -r -c 5 -nocats -mb 150 -ml 500 -mr 500 -mt 150 &
exec-once = $idlehandler &
exec-once = swww-daemon &
exec-once = waypaper --restore &
exec-once = waybar &
exec-once = mako &
exec-once = albert &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 $
exec-once = localsend --hidden &
exec-once = hyprctl setcursor Bibata-Modern-Classic 24 &

