# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


$launcher = albert toggle
$filemanager = nautilus --new-window
$app_drawer = nwg-drawer
$terminal = kitty
$browser = firefox
$idlehandler = hypridle
$capturing = hyprshot -m region
$editor = gnome-text-editor
