# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


$launcher = albert toggle
$filemanager = nautilus --new-window
$app_drawer = nwg-drawer
$terminal = kitty
$browser = /opt/zen-browser-bin/zen-bin
$idlehandler = hypridle
$capturing = hyprshot -m region
$editor = gnome-text-editor
