# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


$menu = albert
$filemanager = nautilus --new-window
$applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
$terminal = kitty
$browser = firefox
$idlehandler = hypridle
$capturing = hyprshot -m region
