# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# Default Apps
env = BROWSER,/opt/zen-browser-bin/zen-bin
#env = BROWSER,firefox
env = TERM,kitty
env = EDITOR,nvim

# Screenshots
env = HYPRSHOT_DIR, /home/noahenyeart/Pictures/Screenshots

# GTK/GDK
env = GDK_BACKEND=wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# QT
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Cursor
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

# GPU Management
env = LIBVA_DRIVER_NAME,iHD				# Default for hardware acceleration
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia			# Default OpenGL renderer



