# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/

monitor = , preferred, auto, 1.25
monitor = eDP-1, 2560x1600@240.00, 0x0, 1.25
monitor = eDP-2, 2560x1600@240.00, 0x0, 1.25
monitor = DP-1, 3840x2160@144.00, 2048x-680, 1.25
monitor = DP-2, 3840x2160@144.00, 2048x-680, 1.25
monitor = HDMI-A-1, 3840x2160@144.00, 2048x-680, 1.25


# Disable internal display when lid closes
bindl = ,switch:on:Lid Switch, exec, hyprctl keyword monitor eDP-1,disable

# Re-enable when lid opens
bindl = ,switch:off:Lid Switch, exec, hyprctl keyword monitor eDP-1,2560x1600@240.00,0x0,1.25


xwayland {
    force_zero_scaling = true       # Unscale XWayland
}


