# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Window Rules Configuration               ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# General #

windowrule {
	name = floating
	persistent_size = on
	center = on
	match:float = true
}


# Top Bar #

windowrule {
	name = hardware_monitor
	float = on
	size = 800 500
	move = (13) (53)
	animation = slide left
	stay_focused = on
	match:class = ^(Status)$
}

windowrule {
	name = khal
	float = on
	# size = 480 368
	move = ((monitor_w*0.5)-(window_w*0.5)) (53)
	animation = slide top
	stay_focused = on
	match:class = ^(khal-popup)$
}

windowrule {
	name = status
	float = on
 	# size = 720 720
	move = (monitor_w-window_w-13) (53)
	animation = slide right
	stay_focused = on
	match:class = ^(org.pulseaudio.pavucontrol|Gazelle|bluetui)$
}


# PIP #

windowrule {
	name = pip
	float = on
	# size = 720 480
	move = (monitor_w-window_w-13) (monitor_h-window_h-13)
	pin = on
	match:title = ^(Picture-in-Picture)$
}


# Popups #

windowrule {
	name = albert
	stay_focused = on
	match:title = ^(Albert)$
}

windowrule {
	name = gnome_prompts
	stay_focused = on
	match:class = ^(polkit-gnome-authentication-agent-1|gcr-prompter)$
}

windowrule {
	name = file_pickers
	float = on
	size = 720 480
	match:class = ^()$
	match:title = ^(Save File|Open File|Pick Files|Please choose a folder)$
}

windowrule {
	name = xdg_popups
	float = on
	match:class = ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
}

windowrule {
	name = polkit_popups
	float = on
	match:class = ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
}

windowrule {
	name = zenity_popups
	float = on
	match:class = ^(zenity)$
}

windowrule {
	name = steam
	float = on
	center = on
	match:class = ^()$
	match:title = ^(Steam - Self Updater)$
}


# Winboat #

windowrule {
	name = winboat
	suppress_event = fullscreen maximize activate activatefocus
	match:class = ^(winboat)(.*)$
}

# Apps #

windowrule {
	name = localsend
	float = on
	size = 480 640
	match:class = ^(localsend)$
}


# Opacity #

#windowrule {
#	name = translucent
#	opacity = 0.9
#	match:class = ^(kitty|org.gnome.TextEditor|org.gnome.Nautilus)$
#}

windowrule {
	name = opaque
	opaque = on
	match:class = ^(firefox|discord)$
}

### Workspaces Rules ###

windowrule {
	name = special_workspace_apps
	workspace = special
	match:class = ^(com.github.wwmm.easyeffects|spotify|discord)$
}


# Monitors #

workspace = 1, default:true, monitor:eDP-1


### Layer Rules ###


layerrule {
	name = waybar
	animation = slide top
	match:namespace = waybar
}

layerrule {
	name = wlogout
	animation = slide top
	match:namespace = logout_dialog
}

layerrule {
	name = nwg-drawer
	animation = slide bottom
	match:namespace = nwg-drawer
}


